---
title: "Assualt_Death_Rates_USA_Vs_OECD_Countries"
author: "Dixita Dineshbhai Mendpara"
date: '2023-05-03'
output: word_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyr)
```


```{r}
assault_data <- read.csv("assault.csv")

new_assault_data <- gather(assault_data, Year, Deaths, -Country)

new_assault_data$Year <- as.numeric(substring(new_assault_data$Year, 2))
new_assault_data$Deaths <- as.numeric(new_assault_data$Deaths)

usa_data <- subset(new_assault_data, Country == "United States")
other_countries_data <- subset(new_assault_data, Country != "United States")

ggplot() +
  # Add data for United States
  geom_jitter(data = usa_data, aes(x = Year, y = Deaths), color = "orange", width = 0.2, height = 0, shape = 19) +
  geom_smooth(data = usa_data, aes(x = Year, y = Deaths), color = "orange", method = "loess", se = FALSE) +
  # Add data for other OECD countries
  geom_jitter(data = other_countries_data, aes(x = Year, y = Deaths, color = "blue"), width = 0.2, height = 0, shape = 19) +
  geom_smooth(data = other_countries_data, aes(x = Year, y = Deaths, color = "blue"), method = "loess", se = FALSE) +
  # Set plot labels and title
  labs(x = "Year", y = "Deaths per 100000 Population", title = "Assault death rates in the OCED 1960-2015") +
  # Set plot theme
  theme_minimal() +
  # Set color scale for countries
  scale_color_manual(name = "Country", values = c(USA = "orange", Other = "blue")) +
  # Set y-axis limits and breaks
  scale_y_continuous(limits = c(0, 8), breaks = c(0, 2, 4, 6, 8)) +
  # Prevent overlapping of points
  coord_cartesian(clip = "off")
```

